server:
  port: 8980
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bblmsa_auth
    username: postgres
    password: sopra*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
