server:
  port: 8980
  use-forward-headers: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bblmsa_auth
    username: postgres
    password: sopra*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
auth:
  oauth2:
    certFilePath: classpath:bblmsacert.jks
    certPassword: sopra*
    clients:
      - id: bblmsa
        secret: bblmsasecret
        authorizedGrantTypes:
          - password
          - refresh_token
        scopes:
          - openid