server:
  port: 8980
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bblmsa_auth
    username: postgres
    password: sopra*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
auth:
  oauth2:
    clients:
      - id: bblmsa
        secret: bblmsasecret
        authorizedGrantTypes:
          - password
          - refresh_token
        scopes:
          - openid