server:
  port: ${port:8180}
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:h2:mem:events:test;DB_CLOSE_DELAY=-1
    username: events
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/