server:
  port: 8080
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
zuul:
  ignoredServices: '*'
  routes:
    event-service:
      path: /event-service/**
    notification-service:
      path: /notification-service/**
    auth-service:
      path: /auth-service/**
      sensitiveHeaders:
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8980/oauth/token
      userAuthorizationUri: http://localhost:8980/oauth/authorize
      clientId: bblmsa
      clientSecret: bblmsasecret
    resource:
      jwt:
        keyValue: bblmsasupersecureprodreadykey