server:
  port: 8080
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
zuul:
  ignoredServices: '*'
  routes:
    event-service:
      path: /event-service/**
    notification-service:
      path: /notification-service/**