server:
  port: ${port:8280}
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:h2:mem:profiles:test;DB_CLOSE_DELAY=-1
    username: profiles
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create