server:
  port: 8180
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:h2:file:./target/h2db/db/events;DB_CLOSE_DELAY=-1
    username: events
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
security:
  basic:
    enabled: false